---
- hosts: all
  remote_user: pi
  become: yes 

  # This runs all the tasks in the /roles/webservers/tasks/main.yml file
  roles:
    - webservers

# Make sure we have Apache installed on our server nodes 
- hosts: nodes 
  remote_user: pi
  become: yes 
  gather_facts: no 
    
  # This runs all the tasks in the /roles/apache2/tasks/main.yml file   
  roles:
    - apache2

# Deploy the custom index file to node 2  
- hosts: node2
  remote_user: pi
  become: yes
  gather_facts: no

  tasks:

    # Change this to whatever directory your Ansible playbook lives in 
    # Ex: /some-folder/another-folder/ansible/python/ledON.py
    - name: Visually indicate which server we are deploying to
      script: /Users/jason/Desktop/websites/ansible/python/ledON.py
      changed_when: false

    # Apache's default web directory is /var/www/html on the Pi
    - name: Deploy updated index.html file 
      copy: 
        src: ./html/index-1.html
        dest: /var/www/html/index.html
        mode: 0644

    # Change this to whatever directory your Ansible playbook lives in 
    # Ex: /some-folder/another-folder/ansible/python/ledON.py
    - name: Visually indicate that we are done deplying to the server
      script: /Users/jason/Desktop/websites/ansible/python/ledOFF.py
      changed_when: false

# Deploy the custom index file to node 3
- hosts: node3
  remote_user: pi
  become: yes
  gather_facts: no

  tasks:

    # Change this to whatever directory your Ansible playbook lives in 
    # Ex: /some-folder/another-folder/ansible/python/ledON.py
    - name: Visually indicate which server we are deploying to
      script: /Users/jason/Desktop/websites/ansible/python/ledON.py 
      changed_when: false
    
    # Apache's default web directory is /var/www/html on the Pi
    - name: Deploy updated index.html file 
      copy: 
        src: ./html/index-2.html
        dest: /var/www/html/index.html
        mode: 0644

    # Change this to whatever directory your Ansible playbook lives in 
    # Ex: /some-folder/another-folder/ansible/python/ledON.py
    - name: Visually indicate that we are done deplying to the server
      script: /Users/jason/Desktop/websites/ansible/python/ledOFF.py
      changed_when: false