---
- hosts: all
  remote_user: pi
  become: yes 

  # This runs all the tasks in the /roles/common/tasks/main.yml file
  roles:
    - common

# Interact with our loadbalancer and ensure HAProxy is up to date
- hosts: loadbalancer
  remote_user: pi
  become: yes 

  # This runs all the tasks in the /roles/webserver/tasks/main.yml file 
  roles:
    - webservers

# Make sure we have Apache installed on our server nodes 
- hosts: nodes 
  remote_user: pi
  become: yes 
  gather_facts: no 
    
  # This runs all the tasks in the /roles/apache2/tasks/main.yml file   
  roles:
    - apache2

  tasks:

    # Change this to whatever directory your Ansible playbook lives in 
    # Ex: /some-folder/another-folder/ansible/python/ledON.py
    - name: Visually indicate which server we are deploying to
      script: ./python/ledON.py 
      changed_when: false
    
    # Apache's default web directory is /var/www/html on the Pi
    - name: Deploy updated index.html file 
      copy: 
        src: "{{ source }}"
        dest: "{{ dest }}"
        mode: 0644

    # Change this to whatever directory your Ansible playbook lives in 
    # Ex: /some-folder/another-folder/ansible/python/ledON.py
    - name: Visually indicate that we are done deplying to the server
      script: ./python/ledOFF.py
      changed_when: false