---
# tasks file for webservers

    - name: Visually indicate which loadbalancer node that we are deploying to
      script: ./python/ledON.py
      changed_when: false

    - name: Check to see that HAProxy is installed
      apt: 
        name: haproxy
        state: present

    - name: Push HAProxy configuration to the loadbalancer
      template:
        src: templates/haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
        owner: root
        group: root
        mode: 0640
      register: update_config

    - name: Restart our HAProxy service
      command: /etc/init.d/haproxy restart
      when: update_config.changed

    - name: Visually indicate that we are done deploying to the node
      script: ./python/ledOFF.py
      changed_when: false